# Don't suggest changing double quoted strings to single quoted strings if they
# don't contain string interpolation.
Style/StringLiterals:
  Enabled: false

# All files in Rails are treated as having a frozen string literal comment.
Style/FrozenStringLiteralComment:
  Enabled: false

# Set max line length to 120 characters.
Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Enabled: true
  Max: 25

# This cop checks the indentation of the method name part in method calls that
# span more than one line.
# Indented forces the following convention
#   while myvariable
#     .a
#     .b
#   end
Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented

# Requires a comma after the last item of all non-empty, multiline array literals.
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

# Requires a comma after the last item of all non-empty, multiline hash literals.
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

# Prevent Rubyocop from naging about using `unless` instead of negative conditions.
Style/NegatedIf:
  Enabled: false

# Check that the keys, separators, and values of a multi-line hash literal are
# aligned according to configuration.
Style/HashAlignment:
  EnforcedColonStyle:
    - table
    - key
